name: Continuous integration icons

on:
  push:
    branches:
      # - main
      - '*'
    # paths:
    #   - icons/**/*.svg

jobs:
  create-release:
    # Only create a new releases for new icons
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: write
      packages: read
      actions: write
      issues: write
      pull-requests: write

    outputs:
      VERSION: ${{ steps.semantic.outputs.new_release_version }}

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2

      - name: Semantic Release
        id: semantic
        uses: cycjimmy/semantic-release-action@v4
        with:
          tag_format: ${version}
          branches: |
            ['new-release-workflow']
          extends: |
            semantic-release-monorepo
          extra_plugins: |
            @semantic-release/github
            @semantic-release/git
            @semantic-release/release-notes-generator
            conventional-changelog-conventionalcommits

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Do something when a new release published
        if: steps.semantic.outputs.new_release_published == 'true'
        run: |
          echo ${{ steps.semantic.outputs.new_release_version }}
          echo ${{ steps.semantic.outputs.new_release_major_version }}
          echo ${{ steps.semantic.outputs.new_release_minor_version }}
          echo ${{ steps.semantic.outputs.new_release_patch_version }}
      # - name: Create Release
      #   uses: softprops/action-gh-release@v1
      #   with:
      #     tag_name: ${{ steps.semantic.outputs.new_release_version }}
      #     name: Version ${{ steps.semantic.outputs.new_release_version }}
      #     body: ${{ steps.semantic.outputs.new_release_notes }}

  # start-release:
  #   if: github.repository == 'lucide-icons/lucide'
  #   needs: create-release
  #   uses: './.github/workflows/release.yml'
  #   secrets: inherit
  #   with:
  #     version: ${{ needs.create-release.outputs.VERSION }}
