name: Continuous integration icons

on:
  push:
    branches:
      - main
    paths:
      - icons/**/*.svg

jobs:
  create-release:
    if: github.repository == 'lucide-icons/lucide'
    runs-on: ubuntu-latest
    outputs:
      VERSION: ${{ steps.semantic.outputs.new_release_version }}

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Semantic Release
        id: semantic
        uses: cycjimmy/semantic-release-action@v4
        with:
          tag_format: ${version}
          extra_plugins: |
            @semantic-release/github
            @semantic-release/git
            @semantic-release/release-notes-generator
            conventional-changelog-conventionalcommits

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.semantic.outputs.new_release_version }}
          name: Version ${{ steps.semantic.outputs.new_release_version }}
          body: ${{ steps.semantic.outputs.new_release_notes }}

  start-release:
    if: github.repository == 'lucide-icons/lucide'
    needs: create-release
    uses: './.github/workflows/release.yml'
    secrets: inherit
    with:
      version: ${{ needs.create-release.outputs.VERSION }}
